#include "mlir/IR/Dialect.h"
#include "QuantumDialect.h.inc" // Generated by tblgen

namespace roc_q {
namespace quantum {

// Dialect initialization: add operations, types, etc.
void QuantumDialect::initialize() {
    addOperations<
#define GET_OP_LIST
#include "QuantumOps.cpp.inc"
    >();
}

} // namespace quantum
} // namespace roc_q
