#include "mlir/IR/Dialect.h"
#include "SimulatorDialect.h.inc" // Generated by tblgen

namespace roc_q {
namespace sim {

void SimulatorDialect::initialize() {
    addOperations<
#define GET_OP_LIST
#include "SimulatorOps.cpp.inc"
    >();
}

} // namespace sim
} // namespace roc_q
