"""Canonical rocQuantum Python API."""

from .backends import distributed_capabilities
from .noise import NoiseModel
from . import spin
from .kernel import (
    QuantumKernel,
    compiler_capabilities,
    compile_and_execute,
    compile_and_execute_async,
    execute,
    execute_async,
    get_state,
    get_state_async,
    kernel,
    observe,
    observe_async,
    sample,
    sample_async,
)
from .operator import (
    HermitianOperator,
    PauliOperator,
    QuantumOperator,
    SparseHamiltonianOperator,
    SumOperator,
    get_expectation_value,
)
from .qvec import qvec
from .gates import (
    cnot,
    cphase,
    cp,
    ccx,
    crx,
    cry,
    crz,
    cswap,
    cx,
    cz,
    fredkin,
    h,
    mcx,
    p,
    phase,
    rx,
    ry,
    rz,
    s,
    sdg,
    swap,
    t,
    tdag,
    tdg,
    toffoli,
    x,
    y,
    z,
)

__all__ = [
    "NoiseModel",
    "spin",
    "distributed_capabilities",
    "QuantumKernel",
    "compiler_capabilities",
    "QuantumOperator",
    "PauliOperator",
    "HermitianOperator",
    "SparseHamiltonianOperator",
    "SumOperator",
    "kernel",
    "compile_and_execute",
    "compile_and_execute_async",
    "execute",
    "execute_async",
    "get_state",
    "get_state_async",
    "sample",
    "sample_async",
    "observe",
    "observe_async",
    "get_expectation_value",
    "qvec",
    "h",
    "x",
    "y",
    "z",
    "s",
    "sdg",
    "t",
    "tdg",
    "tdag",
    "rx",
    "ry",
    "rz",
    "p",
    "phase",
    "cnot",
    "ccx",
    "toffoli",
    "cx",
    "cz",
    "swap",
    "cswap",
    "fredkin",
    "mcx",
    "crx",
    "cry",
    "crz",
    "cp",
    "cphase",
]
