"""Canonical rocQuantum Python API."""

from .noise import NoiseModel
from . import spin
from .kernel import QuantumKernel, compile_and_execute, execute, kernel, observe, sample
from .operator import (
    HermitianOperator,
    PauliOperator,
    QuantumOperator,
    SparseHamiltonianOperator,
    SumOperator,
    get_expectation_value,
)
from .qvec import qvec
from .gates import (
    cnot,
    ccx,
    crx,
    cry,
    crz,
    cswap,
    cx,
    cz,
    fredkin,
    h,
    mcx,
    rx,
    ry,
    rz,
    s,
    sdg,
    swap,
    t,
    toffoli,
    x,
    y,
    z,
)

__all__ = [
    "NoiseModel",
    "spin",
    "QuantumKernel",
    "QuantumOperator",
    "PauliOperator",
    "HermitianOperator",
    "SparseHamiltonianOperator",
    "SumOperator",
    "kernel",
    "compile_and_execute",
    "execute",
    "sample",
    "observe",
    "get_expectation_value",
    "qvec",
    "h",
    "x",
    "y",
    "z",
    "s",
    "sdg",
    "t",
    "rx",
    "ry",
    "rz",
    "cnot",
    "ccx",
    "toffoli",
    "cx",
    "cz",
    "swap",
    "cswap",
    "fredkin",
    "mcx",
    "crx",
    "cry",
    "crz",
]
